### ISSUE TITLE
When running the command, it gives an error

### ISSUE THREAD

**Issue by Ascalonking** [JimDunphy/deploy-zimbra-letsencrypt.sh#11]
When running the command, it gives an error
./acme.sh --issue --dns -d mail.domain-example.com

[Thu 14 Nov 2024 04:05:05 PM UTC] It seems that you are using dns manual mode. Read this link first: https://github.com/acmesh-official/acme.sh/wiki/dns-manual-mode

**Comment by JimDunphy** [comment]
Updated the documentation to make it clearer.
