### ISSUE TITLE
Unable to execute the last restart command in this script with Zimbra 8.7 on Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by myriad007** [JimDunphy/deploy-zimbra-letsencrypt.sh#3]
Hey Jim:
I am unable to run this script in cron as the 'zimbra' user as the script fails on the 'zmcontrol restart' command with the error: 'zmcontrol: command not found". We can't 'su' this command as I get "su: must be run from a terminal".  Without the restart this script is DOA. Any thoughts on how to get Zimbra to restart after successfully installing the cert.?

**Comment by myriad007** [comment]
Found a solution (I think): modify the last command to add a path '/opt/zimbra/bin/zmcontrol restart' although the logger service doesn't start (along with zmlogswatchctl and zmswatch). Though it does start from the command line.

**Comment by JimDunphy** [comment]
Yep that should work. The other methods are to set the PATH variable in the script to where it is installed. For the network version, that would be: 

ie. export PATH=/opt/zimbra/bin:$PATH 

or do something like this from cron as the root user. The dash '-' after su will setup the environment that is inherited by the shell invoking the script. 

su - zimbra -c '/opt/zimbra/letsencrypt/deploy-zimbra-letsencrypt.sh' 

I don't get the terminal flag which sounds like requiretty is set. Running as root would probably disable that feature. 

HTH 

Jim

**Comment by myriad007** [comment]
Well what finally worked was creating the crontab as **root** like so: `5 1 * * * su - zimbra /opt/letsencrypt/deploy-zimbra-letsencrypt.sh` All other incarnations failed to start the logger and its related components.  But when I ran the script in the console it was fine - but in the crontab it broke on `zmcontrol restart`. It is probably a PATH problem with Zimbra's cron as you surmised.

**Comment by JimDunphy** [comment]
Thanks. I'll add that to the recipes. 

Jim
