### ISSUE TITLE
script stopped working, guess it's because of DST Root CA X3 is hardcoded, and has expired...

### ISSUE THREAD

**Issue by marcoteixeira** [JimDunphy/deploy-zimbra-letsencrypt.sh#9]
IdenTrust DST Root CA X3
Please be aware that the "IdenTrust DST Root CA X3" root expiring on 9/30/2021 has been replaced with the "IdenTrust Commercial Root CA 1" self-signed root which is also trusted by the major browsers and root stores since 1/16/2014. You may download the IdenTrust Commercial Root CA 1 at this link: Root Certificate Download.

**Comment by JimDunphy** [comment]
I no longer use this script but did upgrade the script if you need to use it but it has not been tested... see this post for a better way using the acme.sh deploy hook mentioned in this post https://forums.zimbra.org/viewtopic.php?f=15&t=60781&start=110#p301869
